"""
app/models/audit_log.py — AuditLog immutable model.

This model intentionally does NOT inherit BaseTenantModel.
BaseTenantModel contributes updated_at (onupdate) and deleted_at (soft-delete),
both incompatible with append-only semantics (D-01).

AuditLog defines its own minimal set of columns:
  id         — UUID PK, server-generated
  tenant_id  — FK to tenants.id (NOT NULL) — row-level isolation
  fecha_hora — UTC timestamp set on INSERT (server_default)

Additional business columns follow. All are NOT updatable by design; the
immutability trigger in migration 005 enforces this at the DB level (D-02).

Implemented: C-05 (audit-log)
"""
from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import DateTime, ForeignKey, Integer, String, Text, func
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.core.database import Base


class AuditLog(Base):
    """Immutable audit record.

    Every significant domain action writes one row here. No row can ever
    be modified or deleted (trigger + repo design both enforce this).

    Columns:
        id               — UUID PK, generated by PostgreSQL gen_random_uuid()
        tenant_id        — FK to tenants.id (NOT NULL); row-level isolation
        fecha_hora       — UTC timestamp of the action (server_default now())
        actor_id         — UUID of the real acting user (ALWAYS from JWT sub)
        impersonado_id   — UUID of the impersonated user, NULL for normal sessions
        materia_id       — UUID of the related materia, NULL if not applicable
        accion           — action code from AccionAuditoria catalog
        detalle          — structured context as JSONB (nullable)
        filas_afectadas  — number of rows affected by the action (default 0)
        ip               — client IP address (nullable)
        user_agent       — client User-Agent header (nullable)
    """

    __tablename__ = "audit_log"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=func.gen_random_uuid(),
        nullable=False,
    )

    tenant_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("tenants.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
    )

    fecha_hora: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )

    actor_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        nullable=False,
    )

    impersonado_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        nullable=True,
    )

    materia_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        nullable=True,
    )

    accion: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
    )

    detalle: Mapped[dict | None] = mapped_column(
        JSONB,
        nullable=True,
    )

    filas_afectadas: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=0,
        server_default="0",
    )

    ip: Mapped[str | None] = mapped_column(
        String(45),   # IPv4 (15) or IPv6 (45)
        nullable=True,
    )

    user_agent: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
    )
