"""
app/models/base.py — BaseTenantModel mixin for all domain entities.

Every table in the domain (except Tenant itself) inherits this class.
It contributes: UUID primary key (server-generated), tenant_id FK,
created_at / updated_at timestamps, and deleted_at for soft-delete.

Decision references:
  D1 — Mapped[T] / mapped_column() API (SQLAlchemy 2.0 declarative)
  D3 — Soft delete via deleted_at; BaseRepository filters deleted_at IS NULL by default

Implemented: C-02 (core-models-y-tenancy)
"""
from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import DateTime, ForeignKey, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.core.database import Base


class BaseTenantModel(Base):
    """Abstract base class for all domain models that belong to a tenant.

    Subclasses MUST define `__tablename__`. They do NOT need to redefine
    any of the columns below — SQLAlchemy inherits them automatically.

    Columns:
        id          — UUID PK, generated by PostgreSQL gen_random_uuid()
        tenant_id   — FK to tenants.id (NOT NULL); enforces row-level isolation
        created_at  — UTC timestamp set on INSERT (server_default)
        updated_at  — UTC timestamp set on INSERT and updated on every UPDATE
        deleted_at  — NULL means alive; NOT NULL means soft-deleted
    """

    __abstract__ = True

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=func.gen_random_uuid(),
        nullable=False,
    )

    tenant_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("tenants.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )

    deleted_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        default=None,
    )
